initial commit
spinkube/redis-sample pull request #1
Opened 2024-07-30 15:00 UTC by asteurer

2024-07-30 15:02 UTC, asteurer commented
I'm almost certain that the way I'm handling the package versions (latest and semvar) is wrong. Can I have one of you take  a look at the GH actions file and let me know if there's  a better way to do this?

2024-07-30 15:02 UTC, asteurer commented
Also, this PR is solving https://github.com/spinkube/spin-operator/issues/277

2024-07-31 04:32 UTC, bacongobbler requested changes

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +    if: github.event_name == 'push'
this can be removed. Lines 2-5 already perform this logic.

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +      - uses: actions/checkout@v3
The latest version available is v4: https://github.com/actions/checkout?tab=readme-ov-file#usage

```suggestion
      - uses: actions/checkout@v4
```

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +  build-on-push:
```suggestion
  build-and-push:
```

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +          github_token: ${{ github.token }}
lines 17 and 18 can be removed.

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +        uses: actions/setup-go@v3
The latest version is v5: https://github.com/actions/setup-go?tab=readme-ov-file#v5
```suggestion
        uses: actions/setup-go@v5
```

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +          spin registry push ghcr.io/${{ github.repository }}:$RELEASE_VERSION && \
```suggestion
          spin registry push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:$RELEASE_VERSION && \
```

2024-07-31 04:32 UTC, bacongobbler commented on .github/workflows/main.yaml
> +          spin registry push ghcr.io/${{ github.repository }}:latest
```suggestion
          spin registry push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
```

2024-07-31 05:10 UTC, bacongobbler commented on .github/workflows/main.yaml
> +          RELEASE_VERSION=$(yq '.application.version' spin.toml) && \
Have you looked at how spin-operator calculates the RELEASE_VERSION?

```
https://github.com/spinkube/spin-operator/blob/b8421d76181d24060bf2ed66ca78409de4e81b5b/.github/workflows/sample-apps.yaml#L24-L27
```

2024-07-31 05:10 UTC, bacongobbler commented on .github/workflows/main.yaml
> +          spin registry push ghcr.io/${{ github.repository }}:latest
```suggestion
          spin registry push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
```

2024-07-31 05:12 UTC, bacongobbler commented on .github/workflows/main.yaml
> +          spin registry push ghcr.io/${{ github.repository }}:latest
@endocrimes any opinions here on tagging `latest` for spinkube sample apps?

2024-08-02 10:10 UTC, endocrimes commented on .github/workflows/main.yaml
> +          spin registry push ghcr.io/${{ github.owner }}/${{ github.repository }}:latest
```suggestion
          spin registry push ghcr.io/${{ github.owner }}/${{ github.repository }}:$RELEASE_VERSION
```

I wouldn't bother publishing a `latest` image - it mostly results in documentation going stale quicker when you can't rely on pulling the same content.

2024-08-02 10:12 UTC, endocrimes commented on main.go
> +				http.Error(w, fmt.Sprintf("no value found for key '%s'", reqKey), http.StatusBadRequest)
```suggestion
				http.Error(w, fmt.Sprintf("no value found for key '%s'", reqKey), http.StatusNotFound)
```

2024-08-02 10:14 UTC, endocrimes commented on main.go
> +			http.Error(w, fmt.Sprintf("method %v is not supported, so please try again using 'GET' or 'PUT' for the HTTP method", r.Method), http.StatusBadRequest)
```suggestion
			http.Error(w, fmt.Sprintf("method %q is not supported, so please try again using 'GET' or 'PUT' for the HTTP method", r.Method), http.StatusBadRequest)
```

`%q` will automatically quote the value, which is a little nicer

2024-08-02 20:58 UTC, endocrimes approved these changes
Thanks! - I'll give @bacongobbler a chance for a second review but LGTM

2024-08-03 19:30 UTC, bacongobbler approved these changes

2024-08-03 20:26 UTC, merged